rdb:
  host: "redisdb"
  port: "6379"
  db: 0

db:
  host: "postgresdb"
  port: "5432"
  user: "postgres"
  sslmode: "disable"
  name: "postgres"

smtp:
  host: "smtp.gmail.com"
  port: "587"
  email: "IvanMelnikovF@gmail.com"

tokens:
  accessTTL: 15m
  emailTTL: 1h

verification:
  url: "http://localhost:8000/auth/verify-email"